### ISSUE TITLE
Driver for linux

### ISSUE THREAD

**Issue by ShifuSD** [arutar/FrankenDriver#10]
Driver for linux, pls! (ubuntu)

**Comment by arutar** [comment]
Here is a link to the driver please check and let me know if everything works fine!
https://files.fm/down.php?i=egsj5uzsn

**Comment by arutar** [comment]
Added a Linux driver and instructions
https://github.com/arutar/FrankenDriver/issues/11

**Comment by ShifuSD** [comment]
> Here is a link to the driver please check and let me know if everything works fine!
**It's Work! Tnx, men!** 
P.s. Спасибо мужик! Установил на HiveOS, все завелось, правда пришлось просидеть весь вечер!)
P.p.s. Однако для HiveOS совсем другая инструкция нужна.
