### ISSUE TITLE
Naming in GPU-Z/3DMark/etc

### ISSUE THREAD

**Issue by wingcobob** [arutar/FrankenDriver#13]
Hi, is it possible to have an option for the card to remain as "30xx Laptop GPU" rather than "Frankenstein"? I would quite like to submit benchmark scores on hwbot with my card and it looks extremely odd for the name to show up differently there. Thanks

**Comment by arutar** [comment]
Yes, it's possible, but I don't plan to do it anytime soon.

**Comment by aledsav1** [comment]
I actually like the Frankenstien, makes others think?!
