### ISSUE TITLE
ReBAR 3060m

### ISSUE THREAD

**Issue by StalkingMyPerfil** [arutar/FrankenDriver#14]
Hi I'd like to ask if Resizable bar is possible on RTX 3060M? I've been looking around for a way to get it enabled on my BIOS but it just doesn't work
do U know if is possible? if u do so could u tell me how to enable it Thanks !

**Comment by wingcobob** [comment]
Last I looked into it the vbios has to support rebar for it to work, if you look in nvidia control panel -> system information it will tell you if the card supports it. I know my 3070m doesn't

**Comment by arutar** [comment]
Gpu z has determined that there is rebar support!   
I will test the possibility of enabling it in the near future.
![1](https://user-images.githubusercontent.com/116097611/213012077-2ac43df9-6c8a-425c-8268-3af1aeef040c.png)
![2](https://user-images.githubusercontent.com/116097611/213012082-3cba3348-4c33-4b18-810a-578f538d3152.png)

**Comment by arutar** [comment]
The resizable bar is not supported by the firmware. You can try to request the firmware from the manufacturer. And open a dispute about an unsupported feature.

**Comment by arutar** [comment]
I unsuccessfully flashed my card several times in search of a suitable firmware with support for resizable bar.

**Comment by 3nly** [comment]
Is there really no way to get reBAR support on these cards? Feels like it's more of a driver problem than anything else.

**Comment by arutar** [comment]
@3nly The resizable bar is not supported by the firmware.
