### ISSUE TITLE
Problems with fortnite and other games like fall guys

### ISSUE THREAD

**Issue by EliN4til** [arutar/FrankenDriver#19]
I´been playing easy anti cheat games and it worked until now, i´m having the same error of "your gpu ins´t compatible with DX11" and after that, gives me a mesage and a directory of the Nvidia drivers.

**Comment by EliN4til** [comment]
![Captura de pantalla 2023-01-27 231315](https://user-images.githubusercontent.com/100020397/215215425-e3667fb5-33bd-45eb-a926-86f046c248b0.png)

**Comment by EliN4til** [comment]
I have a rtx 3070ti M with the 528 driver

**Comment by arutar** [comment]
https://github.com/arutar/FrankenDriver/issues/6

**Comment by EliN4til** [comment]
okay, im going to use ddu and use that

**Comment by EliN4til** [comment]
Thanks it worked!!!
