### ISSUE TITLE
FPS IN-GAMES Like Minecraft, Roblox

### ISSUE THREAD

**Issue by StalkingMyPerfil** [arutar/FrankenDriver#21]
is it normal to get a LOW FPS amount? I mean it doesn't change when I'm at max settings and low settings
I used to get 258 FPS on low settings and like 70 FPS on max settings on a GTX 1050 TI 4 GB
when I got the RTX 3060M I'm getting 160 on max Settings and 170 on low settings

is there any adjustments I can do or smth else?

**Comment by arutar** [comment]
Do you have vertical synchronization enabled? try disabling it.  
Is ray tracing enabled?

**Comment by StalkingMyPerfil** [comment]
> 

Nope They don't have any of these options enabled

**Comment by StalkingMyPerfil** [comment]
it helped a bit but I don't know if this is because Roblox isn't optimized for the GPU because when I had a GTX 1050 TI I used to get around 270 FPS on low settings but with this one I'm getting only around 202 but thanks alot for the help!

**Comment by dynamo-foundation** [comment]
My experience with the 3060s I have has been quite good in terms of frame rate.  All of the games I tried to run were totally fine and close to the performance of my 3070TI.
