### ISSUE TITLE
EAC problems

### ISSUE THREAD

**Issue by toastie000** [arutar/FrankenDriver#22]
https://streamable.com/beopig
FDriver = FrankenDriver

The streamable clip will explain the issue, but I'll share some more context. The latest FDriver had been working fine for the past 3 weeks, but I was getting awful fps in RDR2 and Tarkov and was curious to know if a previous FDriver would fix this (it did not FYI). I did that yesterday and even played an EAC game after reinstalling the latest FDriver, but today it decided it wanted to have problems. Runs fine under other anti-cheats, although I didn't test BattlEye.

I didn't test 528.02, but I did test 512.95 and 528.24. I reinstalled 528.24 multiple times, and was uninstalling with DDU of course. I am using a 3070m 10DE.249D 10DE.0000.

(Forgot to include the error messages):
![EAC error](https://user-images.githubusercontent.com/55211530/220214753-c4000278-26a6-422c-9dc0-91d8e4020fb0.jpg)

![DirectX Error](https://user-images.githubusercontent.com/55211530/220214760-90e3d4a3-bde4-4c32-8583-c334c505de58.jpg)

**Comment by arutar** [comment]
Have you read the [instruction](https://github.com/arutar/FrankenDriver/issues/6)

**Comment by toastie000** [comment]
Ah, yes. I completely forgot about that when reinstalling the drivers. My apologies.

**Comment by toastie000** [comment]
> Have you read the [instruction](https://github.com/arutar/FrankenDriver/issues/6)?

Ah, yes. I completely forgot about that when reinstalling the drivers. My apologies.
