### ISSUE TITLE
Overclock RTX 3060M

### ISSUE THREAD

**Issue by StalkingMyPerfil** [arutar/FrankenDriver#23]
Hey do u think it is possible to overclock an RTX 3060M without any issues?
because since we are basically "Desktop" users we don't need to undervolt for a better temp since my pc has 3 fans 
and it runs games at 59 - 60 temp

but do u think it is possible to improve at least 10% of my better performance?
and a safely overclocking

**Comment by arutar** [comment]
I think it's possible. 
But I like it better when the graphics card is cold. Moreover, these 10 percent will not have a particularly strong impact.
