### ISSUE TITLE
2080M support?

### ISSUE THREAD

**Issue by MattF42** [arutar/FrankenDriver#27]
Hi,

Do you support the 2070M / 2080M on Linux such as [this one](https://vi.aliexpress.com/item/1005003912746912.html?srcSns=sns_Copy&spreadType=socialShare&bizType=ProductDetail&social_params=20951479937&aff_fcid=92fc673e9906420cae39e47f8ffee260-1683559430311-01637-_mPLHt9m&tt=MG&aff_fsk=_mPLHt9m&aff_platform=default&sk=_mPLHt9m&aff_trace_key=92fc673e9906420cae39e47f8ffee260-1683559430311-01637-_mPLHt9m&shareId=20951479937&businessType=ProductDetail&platform=AE&terminal_id=80675e85183b430ba419deb31d37b4b4&afSmartRedirect=y) or [this one ](https://a.aliexpress.com/_mrmQIqU)

**Comment by arutar** [comment]
@MattF42 Yes, these cards will work fine on Linux.
