### ISSUE TITLE
3060m   249f

### ISSUE THREAD

**Issue by feixiong-cc** [arutar/FrankenDriver#28]

**Comment by feixiong-cc** [comment]
> 你能提供完整的设备 ID 吗？gpu-z f（或示例）的屏幕截图

![屏幕截图 2023-07-28 225157](https://github.com/arutar/FrankenDriver/assets/126548157/ec3f62ad-bfdb-413c-8b40-94d418c64797)

**Comment by feixiong-cc** [comment]
I tried all the drivers on the market and it didn't work, it didn't work in time to install successfully, except for this 458.48, can't use the new driver, can you help me?

**Comment by arutar** [comment]
@feixiong-cc Try this version of [DRIVER](https://drive.google.com/file/d/17QDhHeRtwWoha_C1H8joPmGPuizNlVi_/view?usp=sharing) And after you check if the driver works, please write here

**Comment by feixiong-cc** [comment]
![屏幕截图 2023-07-29 124312](https://github.com/arutar/FrankenDriver/assets/126548157/24ebc10d-f4d6-4dec-99a9-0f169b3896d7)
This driver is still unusable, it can be installed normally without a signature. But it cannot be called.

**Comment by feixiong-cc** [comment]
@arutar

**Comment by arutar** [comment]
@feixiong-cc As I can see the driver has been installed normally. Do you have multiple video cards in your system? What exactly is not working?

**Comment by arutar** [comment]
@feixiong-cc Can you send a device manager screenshot?

**Comment by feixiong-cc** [comment]
@arutar The video card only has NVIDIA Graphics Device, yes, it seems to be installed, but it does not work.     I have tried to install more than 20 versions, but it still does not work, except for the version 27.21.14.5848, it can be normal only when it is in system test mode or when the driver signature is disabled.     Any other version I have installed can be installed normally, but it cannot be used normally,

**Comment by feixiong-cc** [comment]
@arutar 249f this driver ID, because he doesn't have the right signature I guess. So it can't be used, that's my guess. 458.48 contains a signed certificate, so it can be used normally.

**Comment by feixiong-cc** [comment]
![80adcb785d1b1217fa45ab41b9d0081](https://github.com/arutar/FrankenDriver/assets/126548157/de29357d-4b4c-4e9b-b424-531bbe3bc840)

**Comment by feixiong-cc** [comment]
![756b0cd83e295c949a409a482a811de](https://github.com/arutar/FrankenDriver/assets/126548157/a19323e0-2e81-4ec4-91fa-fec7d0ac21a1)

**Comment by arutar** [comment]
I can't figure out what exactly isn't working. In order to check everything and correct the driver, I need such a card.

**Comment by arutar** [comment]
This device is not a RTX 3060!!!

![Error](https://github.com/arutar/FrankenDriver/assets/116097611/50f6b0c3-6014-4e4f-8bca-e97fb82f430d)

**Comment by arutar** [comment]
If you have any additional information please let me know. A2000m version has been added for now

**Comment by feixiong-cc** [comment]
Thank you very much for your help, I have found out the problem, this graphics card is the inner version of the GA104 for RTX A3000M, it is not available on the market, I think you just need to add my device ID to the updated version, it will work correctly, my device ID is, 10DE.249F.3A4DD17AA

**Comment by arutar** [comment]
@feixiong-cc I added support for your A3000m version. Try this version of the [DRIVER](https://drive.google.com/file/d/1oAsWkl-qD2pH8_DaF9w7sYuDLsxijY1F/view?usp=sharing). And after you check if the driver works, please write here

**Comment by feixiong-cc** [comment]
Unfortunately, it is still the same, it can install the driver, but it cannot be used normally, and only version 458.48 can be used normally. Thanks for your help

**Comment by arutar** [comment]
Next driver version, please try it should work [https://drive.google.com/file/d/1U9VxLcJqxjQ8ZUMMEk5ubUncOWVxP518/view?usp=sharing](DRIVER)

**Comment by feixiong-cc** [comment]
It still doesn't work properly, I switched back to the 458 driver it is normal, you can download this [driver](https://drive.google.com/file/d/1NwlPudAYqd_UUu6ATMvJ8liy0o2B_SFe/view) to see if you can find the problem. Thank you so much!

**Comment by play-day-and-night** [comment]
> 还是不能正常工作，我切换回458驱动是正常的，你可以下载这个[驱动](https://drive.google.com/file/d/1NwlPudAYqd_UUu6ATMvJ8liy0o2B_SFe/view)，看看能不能找到问题。非常感谢！

can you give me the 249f vbios, send to 1532288474@qq.com,thank you
