### ISSUE TITLE
3060M Error 43

### ISSUE THREAD

**Issue by CrazyTaxiLA** [arutar/FrankenDriver#29]
Hey,

I am trying to install a 3060M driver using NVCleanInstall, I add the device ID and the driver installs, but I get error 43 and only OpenGL works in GPU-Z. Why is this? How can I get around this issue to not get error 43 and for it to all work properly? I would like to do this on my own without using your excellent drivers that you provide, partly as a learning exercise. Any help would be great! If you help me I will donate as a thanks despite not needing the driver, because I like the project and your work.

**Comment by arutar** [comment]
I don't know why the third party utility doesn't work
