### ISSUE TITLE
Two 3060m in system

### ISSUE THREAD

**Issue by refflex** [arutar/FrankenDriver#31]
Hi
In Windows drivers 537.13 are successfully installed. GPU-Z shows second card not supported CUDA and OpenCL. After reboot black screen. The same situation is with the drivers from the manufacturer. Any chance to fix this?

**Comment by arutar** [comment]
@refflex Try connecting your monitor with a different HDMI slot.

**Comment by arutar** [comment]
@refflex Will it be the same if you leave only the second card?

**Comment by refflex** [comment]
@arutar The cards are flashed with the same BIOS from the manufacturer. Single cards work without problems. I have not tried flashing cards with other bios.

**Comment by arutar** [comment]
@refflex It turns out that the cards work without problems if they are connected one at a time, but if you connect two at the same time, then one of them stops working?

**Comment by refflex** [comment]
@arutar Yes. More precisely, both cards work until the system is rebooted after installing the drivers. And the second card does not support OpenCL and CUDA (this is important).

**Comment by arutar** [comment]
Everything works perfectly on my system.
![Multicard_1](https://github.com/arutar/FrankenDriver/assets/116097611/bbf2a7b6-c300-4057-8f53-0f0d279af56d)
![Multicard_2](https://github.com/arutar/FrankenDriver/assets/116097611/be3cdc93-e26a-46a0-9120-e8fe9f3a7022)
![Multicard_3](https://github.com/arutar/FrankenDriver/assets/116097611/318d7cae-ca4b-48a6-ae4b-faeb474ea8ea)
