### ISSUE TITLE
Procedure to build drivers

### ISSUE THREAD

**Issue by dynamo-foundation** [arutar/FrankenDriver#32]
Greetings!  Can you post a link to the procedure that you use to create these drivers?  I think there is some confusion regarding how to self-sign a driver with the included device ID.  Thanks!

**Comment by arutar** [comment]
@dynamo-foundation To create this driver, I use a lot of third-party utilities. Utilities for signing the driver, special modules for patching, separate utilities for archiving and assembly. The driver creation procedure is a command to which the archived driver from nvidia is passed, as a result, a ready-made driver is obtained. The procedure takes about 10-15 minutes, only self-written modules are used for patching the driver

**Comment by arutar** [comment]
Performance has been increased since version 537.58
