### ISSUE TITLE
Drivers on Mining gpu?

### ISSUE THREAD

**Issue by Skylord4321** [arutar/FrankenDriver#33]
I wonder if it's possible to use these drivers on mining cards since aliexpress is completely flooded with them

**Comment by arutar** [comment]
So far, driver is not support for (P106-090 / P106-100 / P104-100 / P104-101 / P102-100 / CMP 30HX / CMP 40HX / CMP 50HX / CMP 70HX / CMP 90HX ). But perhaps in the near future I will add this support

**Comment by Skylord4321** [comment]
great thanks for telling me, I want to help but unfortunately, I lack experience with modding drivers, however, there is another person on github who has been creating modded drivers for the mining cards (they are working well but still lacking features). So I hope this provides you with some pieces of information about it.
https://github.com/dartraiden/NVIDIA-patcher

**Comment by arutar** [comment]
This is a good project and there is even anti-cheat support. So far, I don't see the point in adding these cards to the frankendriver
