### ISSUE TITLE
3060m not support shaders models 6.5 or higher 

### ISSUE THREAD

**Issue by Sergeyguy** [arutar/FrankenDriver#35]
Alan wake 2 not started on 3060m. Shader models 6.5 not supported

**Comment by arutar** [comment]
Everything works fine on my 3060m
![ALEN_WAKE](https://github.com/arutar/FrankenDriver/assets/116097611/d3478f8b-6f35-4f93-a991-ca77c98ab863)

**Comment by arutar** [comment]
maybe you should try a different driver version
