### ISSUE TITLE
Rebar support

### ISSUE THREAD

**Issue by Jithub123321** [arutar/FrankenDriver#42]
I have updated to the latest driver on 3070m 16gb but resizable bar still is not available despite being on in sbios, is this a GPU bios issue or a driver limitation?

**Comment by arutar** [comment]
@Jithub123321 This is a video card firmware issue.

**Comment by Jithub123321** [comment]
Thank you for clarifying and quick response.

Do you know if its possible to flash the bios successfully without bricking
the card?
