### ISSUE TITLE
Support for rtx 40 series mobile desktop converted Chinese gpu's?

### ISSUE THREAD

**Issue by matsushita1918** [arutar/FrankenDriver#43]
The 40 series mobile gpus just hit the Chinese market for desktop and offer an incredible uplift with fantastic power draw and formfactor, these drivers only say 30 series, but not 40 series. Comparing a fullsize desktop rtx 3080 which literally eats up 350 watts, the rtx 4080 mobile only uses 110 watts and is 1 percent faster and comes with a more compact dual blower setup instead of the huge fullsize version https://www.techpowerup.com/318128/chinese-vendors-are-offering-nvidia-geforce-rtx-4080m-and-rtx-4090m-as-desktop-gpus
https://gpu.userbenchmark.com/Compare/Nvidia-RTX-4080-Laptop-vs-Nvidia-RTX-3080/m2037743vs4080
https://www.techpowerup.com/gpu-specs/geforce-rtx-4080-mobile.c3947 only 110 watts
https://www.techpowerup.com/gpu-specs/geforce-rtx-3080.c3621 a wasteful 320 watts for the same performance. Even then in some situations the 4080m is still better.

**Comment by arutar** [comment]
Starting with version 551.86, the driver will support RTX 4080m and RTX 4090m.
