### ISSUE TITLE
Support for 3060super

### ISSUE THREAD

**Issue by pandaedward** [arutar/FrankenDriver#44]
Greetings,

I managed to get hold of a rare RTX 3060 SUPER 12G according to the seller it is driver locked in. 

![3060super](https://github.com/arutar/FrankenDriver/assets/17075586/f68e8bb3-d2aa-4054-ba19-e5510f45e15a)

Its Device ID begins with 2501 which is unavailable via `nvcleanstall`, and the driver it creates is unusable in any game. 

Could you help please? Happy to subscribe.

**Comment by arutar** [comment]
@pandaedward Support for your card is [ready](https://drive.google.com/file/d/1sLsQeI6Ef2I4qRHmQWC4tVUTUlNyqLSW/view?usp=drive_link). You can test everything and don't forget to subscribe. Write the test results here.
