### ISSUE TITLE
Chatreey TANK Mini PC supporting.

### ISSUE THREAD

**Issue by Katsiuk** [arutar/FrankenDriver#51]
Does this driver work with Chatreey Tank Mini PC (RTX 3080 16 GB)?

**Comment by arutar** [comment]
@Katsiuk Most likely everything will work. If you have a screenshot of gpu-z, send it and I’ll tell you for sure

**Comment by Katsiuk** [comment]
Here is the screenshot.
![image_2024-04-16_203414804](https://github.com/arutar/FrankenDriver/assets/43387210/4ea876cb-8218-4dec-bf99-da53158f4bd7)

**Comment by arutar** [comment]
@Katsiuk Everything will work

**Comment by Katsiuk** [comment]
Thank you.

**Comment by Katsiuk** [comment]
@arutar While installing No_FR_552.22-desktop-win10-win11-64bit-international-dch-whql I got a BSOD.
I was installing according to "Easy Anti-Cheat support! (instruction)".
Here is the dump:
![image](https://github.com/arutar/FrankenDriver/assets/43387210/8a8901d3-444d-40ee-815d-38d7
[041724-9203-01.dmp](https://github.com/arutar/FrankenDriver/files/15014492/041724-9203-01.dmp)
0609050e)
[17.04.2024.txt](https://github.com/arutar/FrankenDriver/files/15014479/17.04.2024.txt)

**Comment by Katsiuk** [comment]
I managed to install on the second try.
FYI.

**Comment by arutar** [comment]
Try [this one](https://drive.google.com/file/d/1sHozEHDG8uxEfhP1uEoko0zs8wENetMP/view?usp=drive_link)

**Comment by Katsiuk** [comment]
@arutar, what is difference between No_FR and this one?
Because I've already installed the "No_FR...".

**Comment by arutar** [comment]
@Katsiuk does everything work?

**Comment by Katsiuk** [comment]
Yes, for now. I need a Game Ready driver so I installed "No_FR_552.22-desktop-win10-win11-64bit-international-dch-whql".

**Comment by Katsiuk** [comment]
@arutar But I got the BSOD on the first try, so that's why I decided to inform you.

**Comment by arutar** [comment]
@Katsiuk If everything works, then nothing needs to be changed.

**Comment by Katsiuk** [comment]
I'll let you know if anything happens.
Thank you,
