### ISSUE TITLE
RTX Super Resolution not active or working?

### ISSUE THREAD

**Issue by Usulyre** [arutar/FrankenDriver#52]
Hi, I am unable to get  RTX Super Resolution to work.

Is this enabled in your drivers?

I can check the box in nvcp but no matter what I do the status never goes active nor is it confirmed to actually be working.

**Comment by arutar** [comment]
@Usulyre 
To enable RTX Super Resolution you will need the latest version of Google Chrome browser, and enable RTX Super Resolution in nvcp and you will need to play videos in full screen mode.

![image](https://github.com/arutar/FrankenDriver/assets/116097611/ef240050-dbc3-47db-92df-be95d95de307)
