### ISSUE TITLE
552.22 driver version error

### ISSUE THREAD

**Issue by kyeseth** [arutar/FrankenDriver#54]
this driver version seems to not like online games such as rust, sea of thieves, squad or even day z. it seems to ask for direct x 11 and 12 support but runs any other offline/story mode game perfectly with no problems driver related. maybe I'm just doing it wrong? i download the version from franken driver, extract it with 7zip then run the setup program and install the driver. I've even done it without extracting the download but it doesn't seem to make a difference at all. help?

**Comment by arutar** [comment]
@kyeseth Have you read the instructions

https://github.com/arutar/FrankenDriver/issues/6
