### ISSUE TITLE
ali express card link 

### ISSUE THREAD

**Issue by kyeseth** [arutar/FrankenDriver#55]
when i click on any of the ali express gpu links i just end up with a white screen? is it meant to start a download or am i just stupid

**Comment by arutar** [comment]
@kyeseth I do not understand the question, frankendriver is a stand-alone project and has nothing to do with sellers from AliExpress. You can download the driver from here and it will work well

**Comment by kyeseth** [comment]
My card is from ali express i got scammed i tried using ur drivers and they
dont seem to work on the games i listed

**Comment by arutar** [comment]
@kyeseth Have you readed [this instruction](https://github.com/arutar/FrankenDriver/issues/6)
