### ISSUE TITLE
Boosty

### ISSUE THREAD

**Issue by aceman101** [arutar/FrankenDriver#59]
Hey Arutar,

Is there any other way to contact you around subscriptions? Boosty does not work for me (i've tried multiple types of cards). I need the latest drivers and happily subscribe but boosty does not work, no matter what.

**Comment by arutar** [comment]
Try this link [Frankendriver](https://app.lava.top/frankendriver)

**Comment by aceman101** [comment]
i will give this a try!

**Comment by aceman101** [comment]
@arutar it works :), thank you!
