### ISSUE TITLE
Error code 43

### ISSUE THREAD

**Issue by namrekayt** [arutar/FrankenDriver#61]
![Capture](https://github.com/user-attachments/assets/17d86d9a-6b42-48ca-be99-06d828c6530f)

**Comment by arutar** [comment]
@namrekayt This message may appear due to a faulty video card. Please send screenshots of GPU-z

**Comment by namrekayt** [comment]
![gpuz1](https://github.com/user-attachments/assets/71c32e8b-e504-4c30-b01a-95f1889159f8)
![gpuz2](https://github.com/user-attachments/assets/b7c906f8-f209-4034-bcc5-8cc09c9c183a)
![gpuz3](https://github.com/user-attachments/assets/d8ed7880-bdfe-4feb-af8f-bcce3aa7e354)

**Comment by arutar** [comment]
@namrekayt try to delete all video drivers with DDU and then reinstall the driver

**Comment by namrekayt** [comment]
Still, the same thing happens

**Comment by arutar** [comment]
@namrekayt If it is possible to connect to another computer - try. But if it does not work on another computer, then the problem is in the video card itself.

**Comment by arutar** [comment]
@namrekayt 
https://youtu.be/qHzO_mRqtAM?si=jrdwlWNSfGehIyxG
Try to install manually 1660 super
And there is a topic on techpowerup
https://www.techpowerup.com/forums/threads/solution-for-black-screen-rtx-3060m-china-gpu-ninja-jieshuo-and-more.315137/
