### ISSUE TITLE
Black screen 3070m

### ISSUE THREAD

**Issue by LeftLMAO** [arutar/FrankenDriver#64]
So I have 3070m jieshuo 2 Hdmi 1 dp it works fine when I put it in my main pc after drivers when the pop-up ask for my permission to install unknown driver it turns black ( tried on both hdmi and mulitple screens + hdmi cables) and won't work till I Uninstall the driver but when I use it In my second pc it works just fine like any brand card is there a way to fix it please?
I tried multiple windows version and iso and 4 of the listed drivers all do the same on my main pc these are some pics for it working fine in my second pc, sorry bout the long talk.

![20241031_105523](https://github.c
![20241031_105509](https://github.com/user-attachments/assets/e617451d-3a92-423e-b670-5e98d16b62ad)
om/user-attachments/assets/e1680b1f-56b9-420d-b2dd-a72116d363f7)
![20241031_105507](https://github.com/user-attachments/assets/df74621f-ead1-40e3-8c3f-1a28b6cc53d9)

**Comment by arutar** [comment]
@LeftLMAO There is a [topic](https://www.techpowerup.com/forums/threads/solution-for-black-screen-rtx-3060m-china-gpu-ninja-jieshuo-and-more.315137/) about that problem on techpowerup

**Comment by LeftLMAO** [comment]
I saw that post and tried doing whats said but didn't work for me but for this "If you dont get screen you can try connect the GPU to a second pci-e slot!" I didn't try it cause my board comes with only 1-16x so i don't know it might work for someone else but for now I just switched my gpus and will work with that till new info comes out about how to fix it.

**Comment by arutar** [comment]
@LeftLMAO try to install manually 1660 super 
https://youtu.be/qHzO_mRqtAM?si=jrdwlWNSfGehIyxG
