### ISSUE TITLE
Mllse RTX3060m 12Gb 

### ISSUE THREAD

**Issue by ByWallkroft** [arutar/FrankenDriver#65]
Hi. I got some problem. Driver  is partially crashing after starting benchmarking/games (look photo)/ Ind i got black screen in games ofc
1. 
![image](https://github.com/user-attachments/assets/ca449cc0-8931-4739-92bf-59473454df43)
2. 
![image](https://github.com/user-attachments/assets/19bf9ac9-4237-4e24-a405-399c2ce04d61)
3. 
![image](https://github.com/user-attachments/assets/681ddd1d-ccef-4a82-98bd-a7a89714ae92)
Sorry for photo (none screenshot), i got troubles with making screenshot at the test stand

**Comment by arutar** [comment]
@ByWallkroft сложно сказать что за проблема. Я бы пробовал на другом компе (рабочем) если проблема повторяется надо отдавать в ремонт видяху. 
А так может быть все что угодно
БП
Винчестер 
Память

**Comment by ByWallkroft** [comment]
> @ByWallkroft сложно сказать что за проблема. Я бы пробовал на другом компе (рабочем) если проблема повторяется надо отдавать в ремонт видяху. А так может быть все что угодно БП Винчестер Память

судя по всему один из банков памяти неисправен

**Comment by ByWallkroft** [comment]
Делал на заведомо исправном компе под 11 виндой, где у меня CMPшка стояла. 
До этого на стенде с 10 виндой та же шляпа. 
Даже упоролся, нашёл того единственного несчастного (пока ждал ответ), что такую же карту продавал, спросил, на каких драйверах у него работало - всё едино.
Так что тему можно закрыть, а карта поедет обратно к продавцу
