### ISSUE TITLE
Windows 7 Version

### ISSUE THREAD

**Issue by q228777** [arutar/FrankenDriver#66]
Could you make such a driver for Windows 7, even if it's not the latest version? Or can you provide instructions on how to modify the driver in Frankenstein?

**Comment by arutar** [comment]
I'll see what I can do about it. Why do you need a version that is no longer supported?

**Comment by q228777** [comment]
I don't use Windows 10. Any version of the driver for the 3070m would work for me.

**Comment by arutar** [comment]
@q228777 Try [this version](https://disk.yandex.ru/d/BZqF6wjKNopsOg)

**Comment by q228777** [comment]
Thank you very much, the driver is working. However, to bypass the error "the signing certificates are not installed", I had to enable the mode for disabling driver signature enforcement and install the driver through the Device Manager. Unfortunately, the NVIDIA Control Panel did not appear. Do you know how this can be resolved?
