### ISSUE TITLE
error 31 in nvidia platforms controller and framework

### ISSUE THREAD

**Issue by igoralexeev** [arutar/FrankenDriver#8]
Восклицательный знак в диспетчере устройств. но вроде бы игрушки идут, адоб премьер кажется работает

Это устройство работает неправильно, т.к. Windows не удается загрузить для него нужные драйверы. (Код 31)

{Операция не выполнена}
Запрошенная операция не выполнена.

Возникла проблема с запуском устройства ROOT\UNNAMED_DEVICE\0001.

Имя драйвера: oem21.inf
GUID класса: {62f9c741-b25a-46ce-b54c-9bccce08b6f2}
Служба: nvpcf
Нижние фильтры: 
Верхние фильтры: 
Проблема: 0x0
Состояние проблемы: 0xC00000E5

windows  11 22H2  22622.607

**Comment by arutar** [comment]
Можно просто удалить это устройство!

**Comment by arutar** [comment]
@igoralexeev Сегодня выложу драйвера без этой ошибки

**Comment by arutar** [comment]
@igoralexeev Выложил пока 512.95 можно Clean Install сделать и ошибка пропадёт!
